# frozen_string_literal: true

class Place < ApplicationRecord
  attribute :geopoint, :st_point, srid: 4326, geographic: true

  scope :by_primary_category, ->(category) { where(primary_categories: category) }

  # Scope for filtering by alternate categories
  scope :by_alternate_category, ->(category) { where("'#{category}' = ANY (alternate_categories)") }

  # overly copy all G types into O
  # because Overture has lower coverage compared to Google
  CATEGORY_MAPPING = {
    'Food and Drink' => {
      'google' => %w[
        american_restaurant
        bakery
        bar
        barbecue_restaurant
        brazilian_restaurant
        breakfast_restaurant
        brunch_restaurant
        cafe
        chinese_restaurant
        coffee_shop
        fast_food_restaurant
        french_restaurant
        greek_restaurant
        hamburger_restaurant
        ice_cream_shop
        indian_restaurant
        indonesian_restaurant
        italian_restaurant
        japanese_restaurant
        korean_restaurant
        lebanese_restaurant
        meal_delivery
        meal_takeaway
        mediterranean_restaurant
        mexican_restaurant
        middle_eastern_restaurant
        pizza_restaurant
        ramen_restaurant
        restaurant
        sandwich_shop
        seafood_restaurant
        spanish_restaurant
        steak_house
        sushi_restaurant
        thai_restaurant
        turkish_restaurant
        vegan_restaurant
        vegetarian_restaurant
        vietnamese_restaurant
      ],
      'overture' => %w[
        acai_bowls
        afghan_restaurant
        african_restaurant
        airport_lounge
        american_restaurant
        arabian_restaurant
        argentine_restaurant
        armenian_restaurant
        asian_fusion_restaurant
        asian_restaurant
        australian_restaurant
        austrian_restaurant
        azerbaijani_restaurant
        bagel_restaurant
        baguettes
        bakery
        bangladeshi_restaurant
        baozi_restaurant
        bar
        bar_and_grill_restaurant
        barbecue_restaurant
        basque_restaurant
        beach_bar
        beer_bar
        beer_garden
        belarusian_restaurant
        belgian_restaurant
        belizean_restaurant
        bistro
        bolivian_restaurant
        brasserie
        brazilian_restaurant
        breakfast_and_brunch_restaurant
        breakfast_restaurant
        brewery
        british_restaurant
        brunch_restaurant
        bubble_tea
        buffet_restaurant
        bulgarian_restaurant
        burger_restaurant
        burmese_restaurant
        cafe
        cafeteria
        cajun_creole_restaurant
        cambodian_restaurant
        canadian_restaurant
        canteen
        caribbean_restaurant
        catalan_restaurant
        champagne_bar
        cheesesteak_restaurant
        chicken_restaurant
        chicken_wings_restaurant
        chilean_restaurant
        chinese_restaurant
        cidery
        cigar_bar
        cocktail_bar
        coffee_roastery
        coffee_shop
        colombian_restaurant
        comfort_food_restaurant
        costa_rican_restaurant
        cuban_restaurant
        curry_sausage_restaurant
        czech_restaurant
        danish_restaurant
        dim_sum_restaurant
        diner
        dive_bar
        diy_foods_restaurant
        dog_meat_restaurant
        dominican_restaurant
        doner_kebab
        drive_thru_bar
        dumpling_restaurant
        eastern_european_restaurant
        eat_and_drink
        ecuadorian_restaurant
        egyptian_restaurant
        empanadas
        ethiopian_restaurant
        european_restaurant
        falafel_restaurant
        fast_food_restaurant
        filipino_restaurant
        fish_and_chips_restaurant
        fish_restaurant
        fishchbroetchen_restaurant
        flatbread_restaurant
        fondue_restaurant
        food_court
        french_restaurant
        gastropub
        gay_bar
        georgian_restaurant
        german_restaurant
        gluten_free_restaurant
        greek_restaurant
        guamanian_restaurant
        guatemalan_restaurant
        haitian_restaurant
        halal_restaurant
        hamburger_restaurant
        haute_cuisine_restaurant
        hawaiian_restaurant
        health_food_restaurant
        himalayan_nepalese_restaurant
        honduran_restaurant
        hong_kong_style_cafe
        hookah_bar
        hot_dog_restaurant
        hotel_bar
        hungarian_restaurant
        iberian_restaurant
        ice_cream_shop
        indian_restaurant
        indo_chinese_restaurant
        indonesian_restaurant
        international_restaurant
        irish_pub
        irish_restaurant
        israeli_restaurant
        italian_restaurant
        jamaican_restaurant
        japanese_restaurant
        jewish_restaurant
        kofta_restaurant
        kombucha
        korean_restaurant
        kosher_restaurant
        kurdish_restaurant
        laotian_restaurant
        latin_american_restaurant
        lebanese_restaurant
        live_and_raw_food_restaurant
        lounge
        malaysian_restaurant
        meal_delivery
        meal_takeaway
        meat_restaurant
        meatball_restaurant
        mediterranean_restaurant
        mexican_restaurant
        middle_eastern_restaurant
        milk_bar
        milkshake_bar
        molecular_gastronomy_restaurant
        mongolian_restaurant
        moroccan_restaurant
        nasi_restaurant
        nicaraguan_restaurant
        nigerian_restaurant
        noodles_restaurant
        norwegian_restaurant
        oriental_restaurant
        pakistani_restaurant
        pan_asian_restaurant
        panamanian_restaurant
        pancake_house
        paraguayan_restaurant
        persian_iranian_restaurant
        peruvian_restaurant
        piadina_restaurant
        piano_bar
        pigs_trotters_restaurant
        pizza_restaurant
        poke
        polish_restaurant
        polynesian_restaurant
        pop_up_restaurant
        portuguese_restaurant
        potato_restaurant
        poutinerie_restaurant
        pub
        puerto_rican_restaurant
        ramen_restaurant
        restaurant
        romanian_restaurant
        rotisserie_chicken_restaurant
        russian_restaurant
        sake_bar
        salad_bar
        salvadoran_restaurant
        sandwich_shop
        scandinavian_restaurant
        schnitzel_restaurant
        scottish_restaurant
        seafood_restaurant
        senegalese_restaurant
        serbo_croation_restaurant
        singaporean_restaurant
        slovakian_restaurant
        smoothie_juice_bar
        soul_food
        soup_restaurant
        south_african_restaurant
        southern_restaurant
        spanish_restaurant
        speakeasy
        sports_bar
        sri_lankan_restaurant
        steak_house
        steakhouse
        sugar_shack
        supper_club
        sushi_restaurant
        swiss_restaurant
        syrian_restaurant
        tabac
        taco_restaurant
        taiwanese_restaurant
        tapas_bar
        tatar_restaurant
        tea_room
        texmex_restaurant
        thai_restaurant
        theme_restaurant
        tiki_bar
        trinidadian_restaurant
        turkish_restaurant
        ukrainian_restaurant
        uruguayan_restaurant
        uzbek_restaurant
        vegan_restaurant
        vegetarian_restaurant
        venezuelan_restaurant
        venison_restaurant
        vermouth_bar
        vietnamese_restaurant
        waffle_restaurant
        whiskey_bar
        wild_game_meats_restaurant
        wine_bar
        wok_restaurant
        wrap_restaurant
      ]
    },
    'Shopping' => {
      'google' => %w[
        bicycle_store
        book_store
        cell_phone_store
        clothing_store
        convenience_store
        department_store
        discount_store
        electronics_store
        furniture_store
        gift_shop
        grocery_store
        hardware_store
        home_goods_store
        home_improvement_store
        jewelry_store
        liquor_store
        market
        pet_store
        shoe_store
        shopping_mall
        sporting_goods_store
        store
        supermarket
        wholesaler
      ],
      'overture' => %w[
        academic_bookstore
        adult_store
        agricultural_seed_store
        antique_store
        appliance_store
        aquatic_pet_store
        archery_shop
        army_and_navy_store
        art_supply_store
        arts_and_crafts
        asian_grocery_store
        atelier
        auction_house
        audio_visual_equipment_store
        auto_parts_and_supply_store
        baby_gear_and_furniture
        back_shop
        bagel_shop
        bakery
        bathroom_fixture_stores
        battery_store
        bazaars
        bedding_and_bath_stores
        beer_wine_and_spirits
        beverage_store
        bicycle_shop
        bicycle_store
        bird_shop
        boat_parts_and_supply_store
        book_store
        books_mags_music_and_video
        bookstore
        boutique
        box_lunch_supplier
        brewing_supply_store
        bridal_shop
        building_supply_store
        butcher_shop
        candle_store
        candy_store
        cannabis_dispensary
        car_auction
        cards_and_stationery_store
        carpet_store
        cell_phone_store
        ceremonial_clothing
        cheese_shop
        children
        chimney_cake_shop
        chocolatier
        christmas_trees
        clothing_rental
        clothing_store
        coffee_and_tea_supplies
        comic_books_store
        computer_store
        concept_shop
        convenience_store
        cooking_classes
        cosmetic_and_beauty_supplies
        costume_store
        craft_shop
        csa_farm
        cupcake_shop
        custom_cakes_shop
        custom_clothing
        custom_t_shirt_store
        customized_merchandise
        dairy_stores
        dance_wear
        delicatessen
        denim_wear_store
        dental_supply_store
        department_store
        designer_clothing
        desserts
        discount_store
        distillery
        dive_shop
        do_it_yourself_store
        donuts
        drone_store
        drugstore
        duty_free_shop
        e_cigarette_store
        educational_supply_store
        electrical_supply_store
        electronics
        electronics_store
        embroidery_and_crochet
        ethical_grocery
        eyewear_and_optician
        fabric_store
        farmers_market
        farming_equipment_store
        fashion
        fashion_accessories_store
        firework_retailer
        fishmonger
        fitness_exercise_equipment
        flatbread
        flea_market
        flooring_store
        florist
        flower_markets
        flowers_and_gifts_shop
        food
        food_delivery_service
        food_stand
        food_truck
        forklift_dealer
        formal_wear_store
        framing_store
        friterie
        frozen_foods
        frozen_yoghurt_shop
        fruits_and_vegetables
        fur_clothing
        furniture_accessory_store
        furniture_store
        gelato
        gemstone_and_mineral
        gift_shop
        gold_buyer
        golf_equipment
        grilling_equipment
        grocery_store
        guitar_store
        gun_and_ammo
        hair_supply_stores
        handbag_stores
        handicraft_shop
        hardware_store
        hat_shop
        health_food_store
        health_market
        hearing_aid_provider
        hearing_aids
        herb_and_spice_shop
        herbal_shop
        hobby_shop
        hockey_equipment
        holiday_decor
        home_and_garden
        home_decor
        home_goods_store
        home_improvement_store
        home_theater_systems_stores
        honey_farm_shop
        horse_equipment_shop
        hot_tubs_and_pools
        hunting_and_fishing_supplies
        hydroponic_gardening
        ice_cream_and_frozen_yoghurt
        ice_cream_shop
        imported_food
        indian_grocery_store
        indian_sweets_shop
        international_grocery_store
        japanese_confectionery_shop
        japanese_grocery_store
        jewelry_store
        kiosk
        kitchen_and_bath
        kitchen_supply_store
        knitting_supply
        korean_grocery_store
        kosher_grocery_store
        lawn_mower_store
        leather_goods
        lighting_store
        linen
        lingerie_store
        liquor_store
        livestock_feed_and_supply_store
        luggage_store
        lumber_store
        macarons
        market
        market_stall
        maternity_wear
        mattress_store
        meat_shop
        medical_supply
        men
        mexican_grocery_store
        military_surplus_store
        mobile_phone_accessories
        mobile_phone_store
        mulled_wine
        music_and_dvd_store
        musical_instrument_store
        newspaper_and_magazines_store
        night_market
        nursery_and_gardening
        office_equipment
        olive_oil
        online_shop
        organic_grocery_store
        orthopedic_shoe_store
        outdoor_furniture_store
        outdoor_gear
        outlet_store
        packing_supply
        paint_store
        paint_your_own_pottery
        party_supply
        pasta_shop
        patisserie_cake_shop
        pawn_shop
        pen_store
        perfume_store
        personal_shopper
        pet_store
        pharmacy
        photography_store_and_services
        piano_store
        pie_shop
        pizza_delivery_service
        playground_equipment_supplier
        plus_size_clothing
        pool_and_billiards
        pop_up_shop
        popcorn_shop
        pretzels
        props
        public_market
        pumpkin_patch
        religious_items
        rental_kiosks
        reptile_shop
        retail
        rice_shop
        rug_store
        russian_grocery_store
        safe_store
        safety_equipment
        sandwich_shop
        saree_shop
        seafood_market
        shaved_ice_shop
        shaved_snow_shop
        shoe_store
        shopping
        shopping_center
        shopping_mall
        shopping_passage
        skate_shop
        ski_and_snowboard_shop
        sleepwear
        smokehouse
        souvenir_shop
        specialty_foods
        specialty_grocery_store
        spiritual_shop
        sporting_goods
        sporting_goods_store
        sports_wear
        stocking
        store
        street_vendor
        sunglasses_store
        supermarket
        superstore
        surf_shop
        swimwear_store
        t_shirt_store
        tabletop_games
        tableware_supplier
        thrift_store
        tile_store
        tire_repair_shop
        tire_shop
        tobacco_shop
        toy_store
        traditional_clothing
        trophy_shop
        uniform_store
        used_bookstore
        used_vintage_and_consignment
        video_and_video_game_rentals
        video_game_store
        vinyl_record_store
        vitamins_and_supplements
        wallpaper_store
        watch_store
        water_store
        welding_supply_store
        wholesale_store
        wholesaler
        wig_store
        window_treatment_store
        wine_tasting_room
        winery
        women
        woodworking_supply_store
      ]
    }
  }.freeze
end
